formSecret: secretValueForGeneratingCSRFTokens
sharedPassword: password
adminPassword: password
enforceHttps: false
emails:
  - notify@example.com
database:
  driver: pdo_mysql
  dbname: applicants
  user: root
  password:
  host: 127.0.0.1
